# -*- coding: utf-8 -*-
"""remove vocals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QnAhHpW9LrW9JLpjXF-xdH9Z7DtazW8Y
"""

pip install librosa matplotlib IPython pedalboard noisereduce

"""# New Section"""

import librosa
from librosa import display
import numpy as np
import IPython.display as ipd
import matplotlib as plt
import soundfile as sf
import pedalboard as pdb
import noisereduce as nr
from pedalboard import Pedalboard, Compressor, Gain

board = Pedalboard()
cps = Compressor(threshold_db=-50, ratio=25)
gn = Gain(gain_db=30)

board.append(cps)
board.append(gn)

y, sr = librosa.load('weird.wav')

S_full, phase = librosa.magphase(librosa.stft(y)) # compute the spectrogram magnitude and phase

ipd.Audio(data=y[100*sr:130*sr], rate=sr) # Play the full song with(0*sr:4000*sr) but this is a 20 sec song in the middle with these calculations

idx = slice(*librosa.time_to_frames([100*130], sr=sr)) # Plot the spectrum
fig, ax = plt.pyplot.subplots()
img = display.specshow(librosa.amplitude_to_db(S_full[:, idx], ref=np.max), y_axis='log', x_axis='time', sr=sr, ax=ax)
# The wiggly lines below are due to the vocal component. Our goal is to separate them from the accompanying instrumentation.
fig.colorbar(img, ax=ax)

# We'll compare frames using cosine similarity, and aggregate similar frames
# by taking their (per-frequency) median value.
#
# To avoid being biased by local continuity, we constrain similar frames to be
# separated by at least 2 seconds.
#
# This suppresses sparse/non-repetetitive deviations from the average spectrum,
# and works well to discard vocal elements.
S_filter = librosa.decompose.nn_filter(S_full, aggregate=np.median, metric='cosine', width=int(librosa.time_to_frames(2, sr=sr)))
# The output of the filter shouldn't be greater than the input
# if we assume signals are additive.  Taking the pointwise minimum
# with the input spectrum forces this.
S_filter = np.minimum(S_full, S_filter) # minimum

# We can also use a margin to reduce bleed between the vocals and instrumentation masks.
# Note: the margins need not be equal for foreground and background separation
margin_i, margin_v = 3, 11  # can be changed to reduce bleeds
power = 3

mask_i = librosa.util.softmask(S_filter, margin_i * (S_full - S_filter), power=power)
mask_v = librosa.util.softmask(S_full - S_filter, margin_v * S_filter, power=power)

# Once we have the masks, simply multiply them with the input spectrum
# to separate the components

S_foreground = mask_v * S_full
S_background = mask_i * S_full

# Plot the same slice, but separated into its foreground and background
fig, ax = plt.pyplot.subplots(nrows=3, sharex=True, sharey=True)
img = display.specshow(librosa.amplitude_to_db(S_full[:, idx], ref=np.max), y_axis='log', x_axis='time', sr=sr, ax=ax[0])
ax[0].set(title='Full Spectrum')
ax[0].label_outer()

display.specshow(librosa.amplitude_to_db(S_background[:, idx], ref=np.max), y_axis='log', x_axis='time', sr=sr, ax=ax[1])
ax[1].set(title='Background Spectrum')
ax[1].label_outer()

display.specshow(librosa.amplitude_to_db(S_foreground[:, idx], ref=np.max), y_axis='log', x_axis='time', sr=sr, ax=ax[2])
ax[2].set(title='Foreground Spectrum')
ax[2].label_outer()

fig.colorbar(img, ax=ax)

# Recover the foreground audio from the masked spectrogram
y_foreground = librosa.istft(S_foreground * phase)
sf.write('Vocals.wav', y_foreground, sr, subtype="PCM_24")
# playback audio
ipd.Audio(data=y_foreground, rate=sr)

# Read audio
data, samplerate = sf.read('Vocals.wav')
# reduce noise
y_reduced_noise = nr.reduce_noise(y=data, sr=samplerate)
# save audio
sf.write('Vocals_reduced.wav', y_reduced_noise, samplerate, subtype="PCM_24")
# load and play audio
data, samplerate = librosa.load('Vocals_reduced.wav')
ipd.Audio('Vocals_reduced.wav')

# Recover the background audio from the masked spectrogram
x_background = librosa.istft(S_background * phase)
# save instrument track and play
sf.write('Instruments.wav', x_background, sr, subtype="PCM_24")
y, sr = librosa.load('Instruments.wav')
ipd.Audio('Instruments.wav')

compressed_vocals = board(y, sr)
ipd.Audio('Vocals.wav')